### ISSUE TITLE
Cloud version of NetSuite node

### ISSUE THREAD

**Issue by weilies** [drudge/n8n-nodes-netsuite#7]
Dear drudge,

Could u help to build a version which work on cloud too? currently we dont have budget to explore the on-prem version.
I managed to have my netsuite run via node program 
https://community.n8n.io/t/netsuite-http-request-using-oauth1/11236/11?u=weilies_chok

but keep getting error when try to migrate the javascript into n8n
![image](https://github.com/user-attachments/assets/c673233b-20aa-4df0-85cd-8a2186f3ad8a)

**Comment by drudge** [comment]
I don't work for n8n so I can't add plugins to the core.
